### ISSUE TITLE
前端登录失败,没有admin_user

### ISSUE THREAD

**Issue by winffy2009** [lee-fx/taptap-api#1]
前端登录失败,没有admin_user,缺少数据库表,能否提供下完整的SQL脚本?十分感谢

**Comment by lee-fx** [comment]
微信 li18347457131





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: winffy2009 ***@***.***&gt;
发送时间: 2022年4月28日 20:26
收件人: lee-fx/taptap-api ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [lee-fx/taptap-api] 前端登录失败,没有admin_user (Issue #1)





 
前端登录失败,没有admin_user,缺少数据库表,能否提供下完整的SQL脚本?十分感谢

**Comment by lee-fx** [comment]
有时间加我微信吧 我五一找一下
li18347457131



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: winffy2009 ***@***.***&gt;
发送时间: 2022年4月28日 20:26
收件人: lee-fx/taptap-api ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [lee-fx/taptap-api] 前端登录失败,没有admin_user (Issue #1)





 
前端登录失败,没有admin_user,缺少数据库表,能否提供下完整的SQL脚本?十分感谢
